package helpers

var NakshatraData = map[string]map[string]interface{}{
	"Ashwini": {
		"Features": "People born under Ashwini Nakshatra are known to be bright, intelligent, helpful and independent. They are passionate about making new beginnings and helping others. They have a strong desire to learn and are determined to achieve their goals.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "0° - 3° 20' Aries",
				"RulingPlanet":    "Mars",
				"Characteristics": "People born in this phase are highly energetic, ambitious and born leaders. They take decisions quickly and are always ready to complete tasks.",
			},
			2: {
				"Pada":            2,
				"Degree":          "3° 20' - 6° 40' Aries",
				"RulingPlanet":    "Mars",
				"Characteristics": "In terms of energy and ambition, the people of this phase are similar to those of the first phase. However, these people are a little more diplomatic and strategic. They believe in planning to achieve their goals.",
			},
			3: {
				"Pada":            3,
				"Degree":          "6° 40' - 10° 00' Aries",
				"RulingPlanet":    "Sun",
				"Characteristics": "People born in this phase are natural leaders. They are confident, kind and worthy of respect. They like to be praised and are able to guide others.",
			},
			4: {
				"Pada":            4,
				"Degree":          "10° 00' - 13° 20' Aries",
				"RulingPlanet":    "Venus",
				"Characteristics": "People born in this phase are rich in creative, artistic and attractive personality. They put others at ease and also have diplomatic skills.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Bright and intelligent", "Description": "People of Ashwini Nakshatra are bright and intelligent. These people learn very quickly. Are skilled in solving problems. Are able to influence the people around them."},
			{"Characteristic": "Independent and ambitious", "Description": "Freedom is paramount for these people. They set their goals and are ready to work hard to achieve them. Challenges do not distract them, but awaken them and motivate them."},
			{"Characteristic": "Assistants and Associates", "Description": "People of Ashwini Nakshatra are always ready to help others. They are kind and charitable in nature."},
			{"Characteristic": "Leader and Motivator", "Description": "People born in Ashwini Nakshatra have innate leadership abilities. They are able to inspire and guide others."},
		},
		"MaleCharacteristics":   "A man born in Ashwini Nakshatra is considered to be enthusiastic, active, and courageous in life. Their nature is full of inspiration and life-giving energy. They welcome new challenges and keep exploring their infinite possibilities. Men born under Ashwini Nakshatra often become a source of inspiration for the people around them and inspire them to achieve their goals through their courageous and excellent examples. It is their nature to always be ready to help others. They have a cooperative and kind nature. Because of their independence and ambition, these people often choose to become entrepreneurs. They are ready to work hard to achieve success in their business. They have creative thinking and skills. They can be successful in various fields, including arts, writing, engineering, etc. These men are dedicated and loyal to their spouses. They believe in maintaining relationships. They are always ready to take care and protect their family.",
		"FemaleCharacteristics": "A woman born in Ashwini Nakshatra is full of energy, inspiration, and a sense of independence in life. She is charming and courageous and determined to achieve her goals. They are inspiring and inspire others to fulfil your dreams. They have a sense of courage and independence. Which makes them introduce their abilities in new and unknown areas. Due to ambition and hard work, these women often achieve success in their professional fields. They can also perform well on the job. They can also establish their own business. They have creative thinking and skills. They can be successful in various fields, including art, design, writing etc. These women are devoted to their spouse and family. They take care of their partner and take the lead in maintaining the home. They are a strong pillar of support for their loved ones and support them in every situation.",
		"Career": []map[string]string{
			{"Career": "Entrepreneurs and Businessmen", "Description": "People of Ashwini Nakshatra are independent and ambitious. They like to be their own boss and are interested in setting up their own business. They have the innate quality of leadership ability and motivating others. They are hard workers and goal achievers."},
			{"Career": "Medical and healthcare", "Description": "The deity of Ashwini Nakshatra is the god of medicine, so these natives naturally have a tendency to take care of others and keep them healthy. They are compassionate and understand the suffering of others. They have a strong desire to learn and can become successful doctors, nurses or researchers in the medical field."},
			{"Career": "Creative field", "Description": "People of Ashwini Nakshatra have creative thinking and skills. They can be successful in various mediums of artistic expression, like painting, writing, designing etc. They have curiosity to learn and experiment with new things."},
			{"Career": "Education and Research", "Description": "People of Ashwini Nakshatra are bright and intelligent. They learn quickly and are eager to acquire knowledge. They can become effective speakers and teachers. They have analytical skills and can also be successful in the field of research."},
		},
	},
	"Bharani": {
		"Features": "People born under Bharani Nakshatra are known for their strong will, independence, and intense energy. They are often seen as authoritative figures and have the ability to influence others. They are passionate about their beliefs and can be very determined in their pursuits.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "13° 20' - 16° 40' Aries",
				"RulingPlanet":    "Venus",
				"Characteristics": "People in this phase are creative, artistic, and have a good sense of aesthetics. They are also very empathetic and caring.",
			},
			2: {
				"Pada":            2,
				"Degree":          "16° 40' - 20° 00' Aries",
				"RulingPlanet":    "Venus",
				"Characteristics": "These individuals are practical, disciplined, and have a strong sense of duty. They are good at managing responsibilities.",
			},
			3: {
				"Pada":            3,
				"Degree":          "20° 00' - 23° 20' Aries",
				"RulingPlanet":    "Venus",
				"Characteristics": "People born in this phase are courageous, active, and love challenges. They are highly energetic and competitive.",
			},
			4: {
				"Pada":            4,
				"Degree":          "23° 20' - 26° 40' Aries",
				"RulingPlanet":    "Venus",
				"Characteristics": "Individuals born in this phase are known for their intellect, curiosity, and love for learning. They can be great scholars or researchers.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Strong-willed and Independent", "Description": "Bharani natives have a strong will and are highly independent. They value their freedom and often take charge of their own lives."},
			{"Characteristic": "Energetic and Passionate", "Description": "They are full of energy and passion. Their intense nature drives them to achieve their goals and excel in their endeavors."},
			{"Characteristic": "Authoritative and Influential", "Description": "These individuals often hold authoritative positions and have the ability to influence others. They are seen as leaders and guides."},
			{"Characteristic": "Creative and Empathetic", "Description": "Bharani natives are creative and have a good sense of aesthetics. They are also empathetic and care deeply about others."},
		},
		"MaleCharacteristics":   "Men born under Bharani Nakshatra are strong-willed, independent, and passionate. They are often seen as leaders and have a natural ability to influence others. They are courageous and love challenges. These men are dedicated to their work and are known for their discipline and sense of duty.",
		"FemaleCharacteristics": "Women born under Bharani Nakshatra are known for their strength, independence, and creativity. They are passionate about their beliefs and are often seen as authoritative figures. They have a good sense of aesthetics and are empathetic and caring.",
		"Career": []map[string]string{
			{"Career": "Leadership Roles", "Description": "Bharani natives have a natural ability to lead and influence others. They are well-suited for leadership roles in various fields."},
			{"Career": "Creative Fields", "Description": "Their creativity and sense of aesthetics make them well-suited for careers in art, design, and other creative fields."},
			{"Career": "Healthcare", "Description": "Their empathetic nature and strong sense of duty make them excellent healthcare professionals, such as doctors, nurses, or caregivers."},
			{"Career": "Research and Education", "Description": "Their intellect and love for learning make them suitable for careers in research and education."},
		},
	},
	"Krittika": {
		"Features": "People born under Krittika Nakshatra are known for their strong determination, courage, and leadership qualities. They have a sharp intellect and are highly ambitious.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "26° 40' Aries - 30° 00' Aries",
				"RulingPlanet":    "Sun",
				"Characteristics": "Individuals born in this phase are courageous, energetic, and possess a strong will to achieve their goals.",
			},
			2: {
				"Pada":            2,
				"Degree":          "00° 00' - 03° 20' Taurus",
				"RulingPlanet":    "Sun",
				"Characteristics": "These individuals are practical, grounded, and have a strong sense of responsibility.",
			},
			3: {
				"Pada":            3,
				"Degree":          "03° 20' - 06° 40' Taurus",
				"RulingPlanet":    "Sun",
				"Characteristics": " Individuals are more focused on material success. They have strong financial acumen and are determined to achieve financial stability.",
			},
			4: {
				"Pada":            4,
				"Degree":          "06° 40' - 10° 00' Taurus",
				"RulingPlanet":    "Sun",
				"Characteristics": "Individuals born in this phase are known for their intellect, curiosity, and love for learning.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Strong Determination", "Description": "Krittika natives are highly determined and never give up easily. They pursue their goals with great intensity."},
			{"Characteristic": "Courageous", "Description": "They possess great courage and are willing to take risks to achieve their objectives."},
			{"Characteristic": "Leadership Qualities", "Description": "These individuals have natural leadership qualities and are often seen guiding and inspiring others."},
			{"Characteristic": "Sharp Intellect", "Description": "Krittika natives have a sharp intellect and are highly knowledgeable."},
		},
		"MaleCharacteristics":   "Men born under Krittika Nakshatra are determined, courageous, and possess strong leadership qualities. They are ambitious and work hard to achieve their goals.",
		"FemaleCharacteristics": "Women born under Krittika Nakshatra are known for their determination, courage, and leadership abilities. They are intelligent and pursue their goals with great passion.",
		"Career": []map[string]string{
			{"Career": "Leadership Roles", "Description": "Krittika natives are well-suited for leadership roles due to their strong determination and courage."},
			{"Career": "Creative Fields", "Description": "Their creativity and sense of aesthetics make them suitable for careers in art, design, and other creative fields."},
			{"Career": "Education", "Description": "Their sharp intellect makes them excellent educators and researchers."},
			{"Career": "Military and Defense", "Description": "Their courage and determination make them well-suited for careers in the military and defense sectors."},
		},
	},
	"Rohini": {
		"Features": "Rohini Nakshatra represents beauty, charm, and fertility. It is symbolized by a chariot, indicating movement and growth.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "10° 00' - 13° 20' Taurus",
				"RulingPlanet":    "Moon",
				"Characteristics": "Individuals born in this pada are attractive, sensual, and possess a love for beauty and art.",
			},
			2: {
				"Pada":            2,
				"Degree":          "13° 20' - 16° 40' Taurus",
				"RulingPlanet":    "Moon",
				"Characteristics": "These individuals are practical, grounded, and have a strong sense of responsibility.",
			},
			3: {
				"Pada":            3,
				"Degree":          "16° 40' - 20° 00' Taurus",
				"RulingPlanet":    "Moon",
				"Characteristics": "People in this pada are practical, hardworking, and possess strong material desires.",
			},
			4: {
				"Pada":            4,
				"Degree":          "20° 00' - 23° 20' Taurus",
				"RulingPlanet":    "Moon",
				"Characteristics": "Individuals are more focused on material success. They have strong financial acumen and are determined to achieve financial stability.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Attractive and Charming", "Description": "Rohini natives are known for their beauty, charm, and sensual nature."},
			{"Characteristic": "Nurturing and Caring", "Description": "They are nurturing and caring, with a strong connection to nature and family."},
			{"Characteristic": "Practical and Hardworking", "Description": "Rohini natives are practical, hardworking, and have a strong desire for material success."},
			{"Characteristic": "Creative and Artistic", "Description": "They possess a creative and artistic nature, with a love for luxury and comfort."},
		},
		"MaleCharacteristics":   "Men born under Rohini Nakshatra are attractive, practical, and hardworking. They are nurturing and have a strong connection to their family.",
		"FemaleCharacteristics": "Women born under Rohini Nakshatra are charming, nurturing, and possess a strong sense of beauty and art. They are practical and have a love for luxury.",
		"Career": []map[string]string{
			{"Career": "Art and Design", "Description": "Rohini natives have a strong sense of beauty and can excel in careers related to art and design."},
			{"Career": "Agriculture and Gardening", "Description": "Their connection to nature makes them suitable for careers in agriculture and gardening."},
			{"Career": "Healthcare and Nurturing Professions", "Description": "They are nurturing and can pursue careers in healthcare and other nurturing professions."},
			{"Career": "Business and Finance", "Description": "Rohini natives are practical and can succeed in business and finance."},
			{"Career": "Luxury Goods and Services", "Description": "Their love for luxury makes them suitable for careers related to luxury goods and services."},
		},
	},
	"Mrigashira": {
		"Features": "Mrigashira Nakshatra represents curiosity, exploration, and searching. It is symbolized by a deer’s head, indicating a gentle and searching nature.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "23° 20' Taurus - 26° 40' Taurus",
				"RulingPlanet":    "Mars",
				"Characteristics": "Individuals born in this pada are curious, adventurous, and possess a strong desire for knowledge.",
			},
			2: {
				"Pada":            2,
				"Degree":          "26° 40' Taurus - 30° 00' Taurus",
				"RulingPlanet":    "Mars",
				"Characteristics": "These individuals are practical, grounded, and have a strong sense of responsibility.",
			},
			3: {
				"Pada":            3,
				"Degree":          "0° 00' - 3° 20' Gemini",
				"RulingPlanet":    "Mars",
				"Characteristics": "People in this pada are adaptable, sociable, and possess a love for travel and exploration.",
			},
			4: {
				"Pada":            4,
				"Degree":          "3° 20' - 6° 40' Gemini",
				"RulingPlanet":    "Mars",
				"Characteristics": "Individuals born in this pada are intense, passionate, and possess a deep desire for change.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Curious and Adventurous", "Description": "Mrigashira natives are known for their curiosity and adventurous nature."},
			{"Characteristic": "Communicative and Intelligent", "Description": "They are communicative, intelligent, and possess a strong sense of curiosity."},
			{"Characteristic": "Adaptable and Sociable", "Description": "Mrigashira natives are adaptable, sociable, and enjoy exploring new places."},
			{"Characteristic": "Innovative and Creative", "Description": "They are innovative and creative, with a strong intellectual curiosity."},
		},
		"MaleCharacteristics":   "Men born under Mrigashira Nakshatra are curious, intelligent, and adventurous. They are communicative and possess a love for exploration.",
		"FemaleCharacteristics": "Women born under Mrigashira Nakshatra are curious, sociable, and adaptable. They are intelligent and possess a strong sense of creativity.",
		"Career": []map[string]string{
			{"Career": "Research and Development", "Description": "Mrigashira natives have a strong sense of curiosity and can excel in research and development."},
			{"Career": "Communication and Media", "Description": "Their communicative nature makes them suitable for careers in communication and media."},
			{"Career": "Travel and Tourism", "Description": "They have a love for exploration and can pursue careers in travel and tourism."},
			{"Career": "Education and Teaching", "Description": "Mrigashira natives are intelligent and can succeed in education and teaching."},
			{"Career": "Creative Arts", "Description": "Their innovative and creative nature makes them suitable for careers in the creative arts."},
		},
	},
	"Ardra": {
		"Features": "Ardra Nakshatra represents transformation, destruction, and renewal. It is symbolized by a teardrop, indicating sorrow and transformation.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "6° 40' - 10° 00' Gemini",
				"RulingPlanet":    "Rahu",
				"Characteristics": "Individuals born in this pada are intense, passionate, and possess a deep desire for change.",
			},
			2: {
				"Pada":            2,
				"Degree":          "10° 00' - 13° 20' Gemini",
				"RulingPlanet":    "Rahu",
				"Characteristics": "These individuals are intelligent, communicative, and have a strong willpower.",
			},
			3: {
				"Pada":            3,
				"Degree":          "13° 20' - 16° 40' Gemini",
				"RulingPlanet":    "Rahu",
				"Characteristics": "People in this pada are adaptable, analytical, and possess a love for learning.",
			},
			4: {
				"Pada":            4,
				"Degree":          "16° 40' - 20° 00' Gemini",
				"RulingPlanet":    "Rahu",
				"Characteristics": "Individuals born in this pada are innovative, creative, and have a strong sense of transformation.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Intense and Passionate", "Description": "Ardra natives are known for their intensity and passion."},
			{"Characteristic": "Intelligent and Communicative", "Description": "They are intelligent, communicative, and possess a strong willpower."},
			{"Characteristic": "Adaptable and Analytical", "Description": "Ardra natives are adaptable, analytical, and have a love for learning."},
			{"Characteristic": "Innovative and Creative", "Description": "They are innovative and creative, with a strong sense of transformation."},
		},
		"MaleCharacteristics":   "Men born under Ardra Nakshatra are intense, passionate, and intelligent. They are communicative and possess a strong willpower.",
		"FemaleCharacteristics": "Women born under Ardra Nakshatra are intense, analytical, and adaptable. They are intelligent and possess a love for learning.",
		"Career": []map[string]string{
			{"Career": "Research and Development", "Description": "Ardra natives have a strong sense of transformation and can excel in research and development."},
			{"Career": "Communication and Media", "Description": "Their communicative nature makes them suitable for careers in communication and media."},
			{"Career": "Psychology and Counseling", "Description": "They have a deep understanding of human emotions and can pursue careers in psychology and counseling."},
			{"Career": "Technology and Innovation", "Description": "Ardra natives are innovative and can succeed in technology and innovation."},
			{"Career": "Creative Arts", "Description": "Their creative nature makes them suitable for careers in the creative arts."},
		},
	},
	"Punarvasu": {
		"Features": "Punarvasu Nakshatra represents renewal, restoration, and return. It is symbolized by a bow and quiver, indicating readiness and preparation.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "20° 00' - 23° 20' Gemini",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "Individuals born in this pada are optimistic, philosophical, and possess a love for learning.",
			},
			2: {
				"Pada":            2,
				"Degree":          "23° 20' - 26° 40' Gemini",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "These individuals are communicative, intelligent, and have a strong sense of ethics.",
			},
			3: {
				"Pada":            3,
				"Degree":          "26° 40' Gemini - 0° 00' Cancer",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "People in this pada are nurturing, caring, and possess a strong connection to family.",
			},
			4: {
				"Pada":            4,
				"Degree":          "0° 00' - 3° 20' Cancer",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "People in this phase are focused on material success, possessing strong financial acumen and determination to achieve financial stability.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Optimistic and Philosophical", "Description": "Punarvasu natives are known for their optimism and philosophical nature."},
			{"Characteristic": "Communicative and Intelligent", "Description": "They are communicative, intelligent, and possess a strong sense of ethics."},
			{"Characteristic": "Nurturing and Caring", "Description": "Punarvasu natives are nurturing, caring, and have a strong connection to family."},
			{"Characteristic": "Emotionally intense and empathetic", "Description": "They feel emotions deeply and understand others' feelings."},
			{"Characteristic": "Adaptable and Flexible", "Description": "They easily adjust to changing circumstances."}
			{"Characteristic": "Financially savvy and focused on material success", "Description": "They manage finances well and aim for financial stability."}
			
		},
		"MaleCharacteristics":   "Men born under Punarvasu Nakshatra are optimistic, philosophical, and communicative. They are nurturing and possess a strong sense of ethics.",
		"FemaleCharacteristics": "Women born under Punarvasu Nakshatra are optimistic, nurturing, and intelligent. They are intuitive and possess a strong sense of spirituality.",
		"Career": []map[string]string{
			{"Career": "Education and Teaching", "Description": "Punarvasu natives have a love for learning and can excel in education and teaching."},
			{"Career": "Communication and Media", "Description": "Their communicative nature makes them suitable for careers in communication and media."},
			{"Career": "Healthcare and Nurturing Professions", "Description": "They are nurturing and can pursue careers in healthcare and other nurturing professions."},
			{"Career": "Philosophy and Spirituality", "Description": "Punarvasu natives are philosophical and can succeed in careers related to philosophy and spirituality."},
			{"Career": "Social Work and Counseling", "Description": "Their caring nature makes them suitable for careers in social work and counseling."},
		},
	},
	"Pushya": {
		"Features": "Pushya Nakshatra represents nourishment, growth, and prosperity. It is symbolized by a cow’s udder, indicating nourishment and nurturing.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "3° 20' - 6° 40' Cancer",
				"RulingPlanet":    "Saturn",
				"Characteristics": "Individuals born in this pada are nurturing, caring, and possess a strong sense of duty.",
			},
			2: {
				"Pada":            2,
				"Degree":          "6° 40' - 10° 00' Cancer",
				"RulingPlanet":    "Saturn",
				"Characteristics": "People in this phase are nurturing, compassionate, and generous, with a strong desire to help others.",
			},
			3: {
				"Pada":            3,
				"Degree":          "10° 00' - 13° 20' Cancer",
				"RulingPlanet":    "Saturn",
				"Characteristics": "These individuals are practical, grounded, and have a strong sense of responsibility.",
			},
			4: {
				"Pada":            4,
				"Degree":          "13° 20' - 16° 40' Cancer",
				"RulingPlanet":    "Saturn",
				"Characteristics": "Individuals born in this pada are creative, artistic, and have a love for luxury and comfort.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Nurturing and Caring", "Description": "Pushya natives are known for their nurturing and caring nature."},
			{"Characteristic": "Disciplined and Responsible", "Description": "They are disciplined, responsible, and possess a strong sense of duty."},
			{"Characteristic": "Practical and Hardworking", "Description": "Pushya natives are practical, hardworking, and have a strong desire for material success."},
			{"Characteristic": "Creative and Artistic", "Description": "They are creative and artistic, with a love for luxury and comfort."},
		},
		"MaleCharacteristics":   "Men born under Pushya Nakshatra are nurturing, disciplined, and practical. They are responsible and possess a strong sense of duty.",
		"FemaleCharacteristics": "Women born under Pushya Nakshatra are nurturing, caring, and artistic. They are disciplined and possess a strong sense of duty.",
		"Career": []map[string]string{
			{"Career": "Healthcare and Nurturing Professions", "Description": "Pushya natives are nurturing and can excel in healthcare and other nurturing professions."},
			{"Career": "Education and Teaching", "Description": "Their caring nature makes them suitable for careers in education and teaching."},
			{"Career": "Business and Finance", "Description": "They are practical and can succeed in business and finance."},
			{"Career": "Art and Design", "Description": "Pushya natives have a creative nature and can pursue careers in art and design."},
			{"Career": "Agriculture and Gardening", "Description": "Their connection to nature makes them suitable for careers in agriculture and gardening."},
		},
	},
	"Ashlesha": {
		"Features": "Ashlesha Nakshatra represents entanglement, control, and mysticism. It is symbolized by a coiled serpent, indicating wisdom and intuition.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "16° 40' - 20° 00' Cancer",
				"RulingPlanet":    "Mercury",
				"Characteristics": "Individuals born in this pada are intuitive, intelligent, and possess a strong sense of control.",
			},
			2: {
				"Pada":            2,
				"Degree":          "20° 00' - 23° 20' Cancer",
				"RulingPlanet":    "Mercury",
				"Characteristics": "These individuals are communicative, analytical, and have a strong connection to mysticism.",
			},
			3: {
				"Pada":            3,
				"Degree":          "23° 20' - 26° 40' Cancer",
				"RulingPlanet":    "Mercury",
				"Characteristics": "Practical and grounded individuals are resourceful, able to make the most out of any situation.",
			},
			4: {
				"Pada":            4,
				"Degree":          "26° 40' Cancer - 0° 00' Leo",
				"RulingPlanet":    "Mercury",
				"Characteristics": "People in this phase are emotionally intense and possess a deep sense of empathy. They are nurturing and supportive.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Intuitive and Intelligent", "Description": "Ashlesha natives are known for their intuition and intelligence."},
			{"Characteristic": "Communicative and Analytical", "Description": "They are communicative, analytical, and possess a strong connection to mysticism."},
			{"Characteristic": "Adaptable and Resourceful", "Description": "Ashlesha natives are adaptable, resourceful, and have a love for knowledge."},
			{"Characteristic": "Secretive and Introspective", "Description": "They are secretive and introspective, with a strong sense of wisdom."},
		},
		"MaleCharacteristics":   "Men born under Ashlesha Nakshatra are intuitive, intelligent, and analytical. They are communicative and possess a strong sense of control.",
		"FemaleCharacteristics": "Women born under Ashlesha Nakshatra are intuitive, resourceful, and intelligent. They are introspective and possess a strong sense of wisdom.",
		"Career": []map[string]string{
			{"Career": "Research and Analysis", "Description": "Ashlesha natives have a strong sense of intuition and can excel in research and analysis."},
			{"Career": "Communication and Media", "Description": "Their communicative nature makes them suitable for careers in communication and media."},
			{"Career": "Psychology and Counseling", "Description": "They have a deep understanding of human emotions and can pursue careers in psychology and counseling."},
			{"Career": "Technology and Innovation", "Description": "Ashlesha natives are innovative and can succeed in technology and innovation."},
			{"Career": "Mysticism and Spirituality", "Description": "Their connection to mysticism makes them suitable for careers related to spirituality and mysticism."},
		},
	},
	"Magha": {
		"Features": "Magha Nakshatra represents power, authority, and leadership. It is symbolized by a throne, indicating sovereignty and dignity.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "0° 00' - 3° 20' Leo",
				"RulingPlanet":    "Ketu",
				"Characteristics": "Individuals born in this pada are authoritative, dignified, and possess a strong sense of leadership.",
			},
			2: {
				"Pada":            2,
				"Degree":          "3° 20' - 6° 40' Leo",
				"RulingPlanet":    "Ketu",
				"Characteristics": "These individuals are ambitious, confident, and have a strong sense of self-respect.",
			},
			3: {
				"Pada":            3,
				"Degree":          "6° 40' - 10° 00' Leo",
				"RulingPlanet":    "Ketu",
				"Characteristics": " Individuals are practical and grounded. They possess a strong sense of responsibility and are dedicated to their work.",
			},
			4: {
				"Pada":            4,
				"Degree":          "10° 00' - 13° 20' Leo",
				"RulingPlanet":    "Ketu",
				"Characteristics": " People in this phase are emotionally intense and possess a deep sense of empathy. They are nurturing and supportive.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Authoritative and Dignified", "Description": "Magha natives are known for their authority and dignity."},
			{"Characteristic": "Ambitious and Confident", "Description": "They are ambitious, confident, and possess a strong sense of self-respect."},
			{"Characteristic": "Generous and Kind-hearted", "Description": "Magha natives are generous, kind-hearted, and have a love for tradition."},
			{"Characteristic": "Creative and Artistic", "Description": "They are creative and artistic, with a strong sense of loyalty."},
		},
		"MaleCharacteristics":   "Men born under Magha Nakshatra are authoritative, ambitious, and dignified. They are generous and possess a strong sense of leadership.",
		"FemaleCharacteristics": "Women born under Magha Nakshatra are ambitious, confident, and kind-hearted. They are creative and possess a strong sense of loyalty.",
		"Career": []map[string]string{
			{"Career": "Leadership and Management", "Description": "Magha natives have a strong sense of authority and can excel in leadership and management."},
			{"Career": "Government and Administration", "Description": "Their dignified nature makes them suitable for careers in government and administration."},
			{"Career": "Creative Arts", "Description": "They have a creative nature and can pursue careers in the creative arts."},
			{"Career": "Tradition and Culture", "Description": "Magha natives have a love for tradition and can succeed in careers related to culture and heritage."},
			{"Career": "Social Work and Counseling", "Description": "Their generous nature makes them suitable for careers in social work and counseling."},
		},
	},
	"PurvaPhalguni": {
		"Features": "People born under Purva Phalguni Nakshatra are known for their charming and charismatic nature. They possess a strong sense of aesthetics and are often very talented in various forms of art. They are also known for their sociable and friendly nature.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "13° 20' - 16° 40' Leo",
				"RulingPlanet":    "Venus",
				"Characteristics": "Individuals born in this pada are charming, sociable, and possess a love for luxury.",
			},
			2: {
				"Pada":            2,
				"Degree":          "16° 40' - 20° 00' Leo",
				"RulingPlanet":    "Venus",
				"Characteristics": "People in this phase are sociable and friendly. They enjoy being around people and have a strong desire to make connections.",
			},
			3: {
				"Pada":            3,
				"Degree":          "20° 00' - 23° 20' Leo",
				"RulingPlanet":    "Venus",
				"Characteristics": " Individuals are practical and grounded. They possess a strong sense of responsibility and are dedicated to their work.",
			},
			4: {
				"Pada":            4,
				"Degree":          "23° 20'  - 0° 00' Leo",
				"RulingPlanet":    "Venus",
				"Characteristics": "Individuals born in this pada are diplomatic, sociable, and have a strong sense of harmony.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Charming and Sociable", "Description": "Purva Phalguni natives are known for their charm and sociability."},
			{"Characteristic": "Creative and Artistic", "Description": "They are creative, artistic, and possess a strong sense of aesthetics."},
			{"Characteristic": "Passionate and Romantic", "Description": "Purva Phalguni natives are passionate, romantic, and enjoy the pleasures of life."},
			{"Characteristic": "Diplomatic and Harmonious", "Description": "They are diplomatic and sociable, with a strong sense of harmony."},
		},
		"MaleCharacteristics":   "Men born under Purva Phalguni Nakshatra are charming, creative, and sociable. They are passionate and possess a strong sense of aesthetics.",
		"FemaleCharacteristics": "Women born under Purva Phalguni Nakshatra are charming, artistic, and romantic. They are diplomatic and possess a strong sense of harmony.",
		"Career": []map[string]string{
			{"Career": "Art and Design", "Description": "Purva Phalguni natives have a strong sense of aesthetics and can excel in art and design."},
			{"Career": "Entertainment and Media", "Description": "Their sociable nature makes them suitable for careers in entertainment and media."},
			{"Career": "Hospitality and Tourism", "Description": "They are charming and can pursue careers in hospitality and tourism."},
			{"Career": "Diplomacy and Public Relations", "Description": "Purva Phalguni natives are diplomatic and can succeed in diplomacy and public relations."},
			{"Career": "Fashion and Beauty", "Description": "Their love for luxury makes them suitable for careers in fashion and beauty."},
		},
	},
	"UttaraPhalguni": {
		"Features": "Uttara Phalguni Nakshatra represents service, charity, and kindness. It is symbolized by a bed, indicating comfort and generosity.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "0° 00' - 3° 20' Virgo",
				"RulingPlanet":    "Sun",
				"Characteristics": "Individuals born in this pada are generous, kind-hearted, and possess a strong sense of duty.",
			},
			2: {
				"Pada":            2,
				"Degree":          "3° 20' - 6° 40' Virgo",
				"RulingPlanet":    "Sun",
				"Characteristics": "These individuals are disciplined, responsible, and have a strong connection to service.",
			},
			3: {
				"Pada":            3,
				"Degree":          "6° 40' - 10° 00' Virgo",
				"RulingPlanet":    "Sun",
				"Characteristics": "People in this pada are practical, hardworking, and possess a strong desire for material success.",
			},
			4: {
				"Pada":            4,
				"Degree":          "10° 00' - 13° 20' Virgo",
				"RulingPlanet":    "Sun",
				"Characteristics": "Individuals born in this pada are creative, artistic, and have a love for luxury and comfort.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Generous and Kind-hearted", "Description": "Uttara Phalguni natives are known for their generosity and kindness."},
			{"Characteristic": "Disciplined and Responsible", "Description": "They are disciplined, responsible, and possess a strong sense of duty."},
			{"Characteristic": "Practical and Hardworking", "Description": "Uttara Phalguni natives are practical, hardworking, and have a strong desire for material success."},
			{"Characteristic": "Creative and Artistic", "Description": "They are creative and artistic, with a love for luxury and comfort."},
		},
		"MaleCharacteristics":   "Men born under Uttara Phalguni Nakshatra are generous, disciplined, and practical. They are responsible and possess a strong sense of duty.",
		"FemaleCharacteristics": "Women born under Uttara Phalguni Nakshatra are generous, kind-hearted, and artistic. They are disciplined and possess a strong sense of duty.",
		"Career": []map[string]string{
			{"Career": "Healthcare and Service Professions", "Description": "Uttara Phalguni natives are nurturing and can excel in healthcare and other service professions."},
			{"Career": "Education and Teaching", "Description": "Their caring nature makes them suitable for careers in education and teaching."},
			{"Career": "Business and Finance", "Description": "They are practical and can succeed in business and finance."},
			{"Career": "Art and Design", "Description": "Uttara Phalguni natives have a creative nature and can pursue careers in art and design."},
			{"Career": "Hospitality and Tourism", "Description": "Their generous nature makes them suitable for careers in hospitality and tourism."},
		},
	},
	"Hasta": {
		"Features": "Hasta Nakshatra represents skill, dexterity, and craftsmanship. It is symbolized by an open hand, indicating skill and dexterity.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "10° 00' - 13° 20' Virgo",
				"RulingPlanet":    "Moon",
				"Characteristics": "Individuals born in this pada are skilled, dexterous, and possess a strong sense of craftsmanship.",
			},
			2: {
				"Pada":            2,
				"Degree":          "13° 20' - 16° 40' Virgo",
				"RulingPlanet":    "Moon",
				"Characteristics": "These individuals are practical, hardworking, and have a strong connection to service.",
			},
			3: {
				"Pada":            3,
				"Degree":          "16° 40' - 20° 00' Virgo",
				"RulingPlanet":    "Moon",
				"Characteristics": "People in this pada are creative, artistic, and possess a love for beauty.",
			},
			4: {
				"Pada":            4,
				"Degree":          "20° 00' - 23° 20' Virgo",
				"RulingPlanet":    "Moon",
				"Characteristics": "Individuals born in this pada are intuitive, emotional, and have a strong sense of compassion.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Skilled and Dexterous", "Description": "Hasta natives are known for their skill and dexterity."},
			{"Characteristic": "Practical and Hardworking", "Description": "They are practical, hardworking, and possess a strong sense of craftsmanship."},
			{"Characteristic": "Creative and Artistic", "Description": "Hasta natives are creative, artistic, and have a love for beauty."},
			{"Characteristic": "Intuitive and Compassionate", "Description": "They are intuitive and emotional, with a strong sense of compassion."},
		},
		"MaleCharacteristics":   "Men born under Hasta Nakshatra are skilled, practical, and hardworking. They are creative and possess a strong sense of craftsmanship.",
		"FemaleCharacteristics": "Women born under Hasta Nakshatra are skilled, artistic, and intuitive. They are compassionate and possess a strong sense of craftsmanship.",
		"Career": []map[string]string{
			{"Career": "Craftsmanship and Artistry", "Description": "Hasta natives have a strong sense of skill and can excel in craftsmanship and artistry."},
			{"Career": "Healthcare and Service Professions", "Description": "Their compassionate nature makes them suitable for careers in healthcare and other service professions."},
			{"Career": "Business and Finance", "Description": "They are practical and can succeed in business and finance."},
			{"Career": "Design and Fashion", "Description": "Hasta natives have a creative nature and can pursue careers in design and fashion."},
			{"Career": "Hospitality and Tourism", "Description": "Their intuitive nature makes them suitable for careers in hospitality and tourism."},
		},
	},
	"Chitra": {
		"Features": "Chitra Nakshatra represents beauty, creation, and craftsmanship. It is symbolized by a bright jewel, indicating brilliance and beauty.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "23° 20' Virgo - 0° 00' Libra",
				"RulingPlanet":    "Mars",
				"Characteristics": "Individuals born in this pada are energetic, dynamic, and possess a strong sense of beauty.",
			},
			2: {
				"Pada":            2,
				"Degree":          "0° 00' - 3° 20' Libra",
				"RulingPlanet":    "Mars",
				"Characteristics": "These individuals are creative, artistic, and have a strong connection to craftsmanship.",
			},
			3: {
				"Pada":            3,
				"Degree":          "3° 20' - 6° 40' Libra",
				"RulingPlanet":    "Mars",
				"Characteristics": "People in this pada are passionate, romantic, and possess a love for beauty.",
			},
			4: {
				"Pada":            4,
				"Degree":          "6° 40' - 10° 00' Libra",
				"RulingPlanet":    "Mars",
				"Characteristics": "Individuals born in this pada are diplomatic, sociable, and have a strong sense of harmony.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Energetic and Dynamic", "Description": "Chitra natives are known for their energy and dynamism."},
			{"Characteristic": "Creative and Artistic", "Description": "They are creative, artistic, and possess a strong sense of beauty."},
			{"Characteristic": "Passionate and Romantic", "Description": "Chitra natives are passionate, romantic, and enjoy the pleasures of life."},
			{"Characteristic": "Diplomatic and Harmonious", "Description": "They are diplomatic and sociable, with a strong sense of harmony."},
		},
		"MaleCharacteristics":   "Men born under Chitra Nakshatra are energetic, creative, and dynamic. They are passionate and possess a strong sense of beauty.",
		"FemaleCharacteristics": "Women born under Chitra Nakshatra are creative, artistic, and romantic. They are diplomatic and possess a strong sense of harmony.",
		"Career": []map[string]string{
			{"Career": "Art and Design", "Description": "Chitra natives have a strong sense of beauty and can excel in art and design."},
			{"Career": "Craftsmanship and Artistry", "Description": "Their creative nature makes them suitable for careers in craftsmanship and artistry."},
			{"Career": "Entertainment and Media", "Description": "They are dynamic and can succeed in entertainment and media."},
			{"Career": "Diplomacy and Public Relations", "Description": "Chitra natives are diplomatic and can pursue careers in diplomacy and public relations."},
			{"Career": "Fashion and Beauty", "Description": "Their love for beauty makes them suitable for careers in fashion and beauty."},
		},
	},
	"Swati": {
		"Features": "Swati Nakshatra represents independence, flexibility, and strength. It is symbolized by a young plant blowing in the wind, indicating resilience and adaptability.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "6° 40' - 10° 00' Libra",
				"RulingPlanet":    "Rahu",
				"Characteristics": "Individuals born in this pada are independent, resilient, and possess a strong sense of adaptability.",
			},
			2: {
				"Pada":            2,
				"Degree":          "10° 00' - 13° 20' Libra",
				"RulingPlanet":    "Rahu",
				"Characteristics": "These individuals are flexible, resourceful, and have a strong connection to strength.",
			},
			3: {
				"Pada":            3,
				"Degree":          "13° 20' - 16° 40' Libra",
				"RulingPlanet":    "Rahu",
				"Characteristics": "People in this pada are innovative, creative, and possess a love for knowledge.",
			},
			4: {
				"Pada":            4,
				"Degree":          "16° 40' - 20° 00' Libra",
				"RulingPlanet":    "Rahu",
				"Characteristics": "Individuals born in this pada are diplomatic, sociable, and have a strong sense of harmony.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Independent and Resilient", "Description": "Swati natives are known for their independence and resilience."},
			{"Characteristic": "Flexible and Resourceful", "Description": "They are flexible, resourceful, and possess a strong sense of strength."},
			{"Characteristic": "Innovative and Creative", "Description": "Swati natives are innovative, creative, and have a love for knowledge."},
			{"Characteristic": "Diplomatic and Harmonious", "Description": "They are diplomatic and sociable, with a strong sense of harmony."},
		},
		"MaleCharacteristics":   "Men born under Swati Nakshatra are independent, resilient, and flexible. They are innovative and possess a strong sense of adaptability.",
		"FemaleCharacteristics": "Women born under Swati Nakshatra are independent, creative, and resilient. They are diplomatic and possess a strong sense of harmony.",
		"Career": []map[string]string{
			{"Career": "Business and Entrepreneurship", "Description": "Swati natives have a strong sense of independence and can excel in business and entrepreneurship."},
			{"Career": "Research and Development", "Description": "Their innovative nature makes them suitable for careers in research and development."},
			{"Career": "Communication and Media", "Description": "They are flexible and can succeed in communication and media."},
			{"Career": "Technology and Innovation", "Description": "Swati natives are creative and can pursue careers in technology and innovation."},
			{"Career": "Diplomacy and Public Relations", "Description": "Their diplomatic nature makes them suitable for careers in diplomacy and public relations."},
		},
	},
	"Vishakha": {
		"Features": "Vishakha Nakshatra represents determination, goal-orientation, and ambition. It is symbolized by a triumphal archway, signifying victory and achievement.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "20° 00' - 23° 20' Libra",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "Individuals born in this pada are ambitious, goal-oriented, and possess strong leadership qualities.",
			},
			2: {
				"Pada":            2,
				"Degree":          "23° 20' - 26° 40' Libra",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "These individuals are determined, focused, and have a strong sense of purpose.",
			},
			3: {
				"Pada":            3,
				"Degree":          "26° 40' Libra - 0° 00' Scorpio",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "People in this pada are resourceful, strategic, and have a strong willpower.",
			},
			4: {
				"Pada":            4,
				"Degree":          "0° 00' - 3° 20' Scorpio",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "Individuals born in this pada are passionate, intense, and possess a strong desire to achieve their goals.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Determined and Ambitious", "Description": "Vishakha natives are highly determined and ambitious, always striving to achieve their goals."},
			{"Characteristic": "Goal-Oriented", "Description": "They are goal-oriented and possess a strong sense of purpose."},
			{"Characteristic": "Resourceful and Strategic", "Description": "They are resourceful and strategic in their approach to achieving success."},
			{"Characteristic": "Passionate and Intense", "Description": "Vishakha natives are passionate and intense, driven by their desire to succeed."},
		},
		"MaleCharacteristics":   "Men born under Vishakha Nakshatra are determined, goal-oriented, and ambitious. They possess strong leadership qualities and a strategic approach to achieving success.",
		"FemaleCharacteristics": "Women born under Vishakha Nakshatra are ambitious, focused, and possess a strong sense of purpose. They are passionate and resourceful in their pursuits.",
		"Career": []map[string]string{
			{"Career": "Leadership Roles", "Description": "Vishakha natives possess strong leadership qualities and can excel in various leadership roles."},
			{"Career": "Strategic Planning", "Description": "Their strategic thinking makes them suitable for careers in strategic planning and management."},
			{"Career": "Business and Entrepreneurship", "Description": "They have a strong sense of purpose and determination, leading to success in business and entrepreneurship."},
			{"Career": "Research and Development", "Description": "Their resourcefulness makes them well-suited for careers in research and development."},
			{"Career": "Creative Fields", "Description": "Vishakha natives can also excel in creative fields due to their passion and intensity."},
		},
	},
	"Anuradha": {
		"Features": "Anuradha Nakshatra represents success, growth, and friendship. It is symbolized by a lotus, indicating spiritual growth and blossoming.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "3° 20' - 6° 40' Scorpio",
				"RulingPlanet":    "Saturn",
				"Characteristics": "Individuals born in this pada are ambitious, disciplined, and possess a strong sense of growth.",
			},
			2: {
				"Pada":            2,
				"Degree":          "6° 40' - 10° 00' Scorpio",
				"RulingPlanet":    "Saturn",
				"Characteristics": "These individuals are sociable, friendly, and have a strong connection to success.",
			},
			3: {
				"Pada":            3,
				"Degree":          "10° 00' - 13° 20' Scorpio",
				"RulingPlanet":    "Saturn",
				"Characteristics": "People in this pada are intuitive, creative, and possess a love for spiritual growth.",
			},
			4: {
				"Pada":            4,
				"Degree":          "13° 20' - 16° 40' Scorpio",
				"RulingPlanet":    "Saturn",
				"Characteristics": "Individuals born in this pada are emotional, compassionate, and have a strong sense of friendship.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Ambitious and Disciplined", "Description": "Anuradha natives are known for their ambition and discipline."},
			{"Characteristic": "Sociable and Friendly", "Description": "They are sociable, friendly, and possess a strong sense of success."},
			{"Characteristic": "Intuitive and Creative", "Description": "Anuradha natives are intuitive, creative, and have a love for spiritual growth."},
			{"Characteristic": "Emotional and Compassionate", "Description": "They are emotional and compassionate, with a strong sense of friendship."},
		},
		"MaleCharacteristics":   "Men born under Anuradha Nakshatra are ambitious, disciplined, and sociable. They are intuitive and possess a strong sense of growth.",
		"FemaleCharacteristics": "Women born under Anuradha Nakshatra are disciplined, friendly, and intuitive. They are compassionate and possess a strong sense of friendship.",
		"Career": []map[string]string{
			{"Career": "Business and Entrepreneurship", "Description": "Anuradha natives have a strong sense of ambition and can excel in business and entrepreneurship."},
			{"Career": "Research and Development", "Description": "Their intuitive nature makes them suitable for careers in research and development."},
			{"Career": "Healthcare and Service Professions", "Description": "They are compassionate and can succeed in healthcare and other service professions."},
			{"Career": "Art and Design", "Description": "Anuradha natives are creative and can pursue careers in art and design."},
			{"Career": "Spirituality and Mysticism", "Description": "Their connection to spiritual growth makes them suitable for careers related to spirituality and mysticism."},
		},
	},
	"Jyeshtha": {
		"Features": "Jyeshtha Nakshatra represents leadership, power, and seniority. It is symbolized by an earring, indicating authority and protection.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "16° 40' - 20° 00' Scorpio",
				"RulingPlanet":    "Mercury",
				"Characteristics": "Individuals born in this pada are authoritative, powerful, and possess a strong sense of leadership.",
			},
			2: {
				"Pada":            2,
				"Degree":          "20° 00' - 23° 20' Scorpio",
				"RulingPlanet":    "Mercury",
				"Characteristics": "These individuals are protective, responsible, and have a strong connection to power.",
			},
			3: {
				"Pada":            3,
				"Degree":          "23° 20' - 26° 40' Scorpio",
				"RulingPlanet":    "Mercury",
				"Characteristics": "People in this pada are ambitious, disciplined, and possess a love for seniority.",
			},
			4: {
				"Pada":            4,
				"Degree":          "26° 40' Scorpio - 0° 00' Sagittarius",
				"RulingPlanet":    "Mercury",
				"Characteristics": "Individuals born in this pada are responsible, authoritative, and have a strong sense of protection.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Authoritative and Powerful", "Description": "Jyeshtha natives are known for their authority and power."},
			{"Characteristic": "Protective and Responsible", "Description": "They are protective, responsible, and possess a strong sense of leadership."},
			{"Characteristic": "Ambitious and Disciplined", "Description": "Jyeshtha natives are ambitious, disciplined, and have a love for seniority."},
			{"Characteristic": "Responsible and Authoritative", "Description": "They are responsible and authoritative, with a strong sense of protection."},
		},
		"MaleCharacteristics":   "Men born under Jyeshtha Nakshatra are authoritative, powerful, and disciplined. They are protective and possess a strong sense of leadership.",
		"FemaleCharacteristics": "Women born under Jyeshtha Nakshatra are responsible, ambitious, and authoritative. They are protective and possess a strong sense of power.",
		"Career": []map[string]string{
			{"Career": "Leadership and Administration", "Description": "Jyeshtha natives have a strong sense of authority and can excel in leadership and administration."},
			{"Career": "Security and Protection Services", "Description": "Their protective nature makes them suitable for careers in security and protection services."},
			{"Career": "Politics and Government", "Description": "They are powerful and can succeed in politics and government."},
			{"Career": "Business and Entrepreneurship", "Description": "Jyeshtha natives are ambitious and can pursue careers in business and entrepreneurship."},
			{"Career": "Research and Development", "Description": "Their disciplined nature makes them suitable for careers in research and development."},
		},
	},
	"Mool": {
		"Features": "Mool Nakshatra represents roots, foundation, and transformation. It is symbolized by a tied bunch of roots, indicating stability and grounding.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "0° 00' - 3° 20' Sagittarius",
				"RulingPlanet":    "Ketu",
				"Characteristics": "Individuals born in this pada are stable, grounded, and possess a strong sense of foundation.",
			},
			2: {
				"Pada":            2,
				"Degree":          "3° 20' - 6° 40' Sagittarius",
				"RulingPlanet":    "Ketu",
				"Characteristics": "These individuals are transformative, resilient, and have a strong connection to stability.",
			},
			3: {
				"Pada":            3,
				"Degree":          "6° 40' - 10° 00' Sagittarius",
				"RulingPlanet":    "Ketu",
				"Characteristics": "People in this pada are analytical, investigative, and possess a love for grounding.",
			},
			4: {
				"Pada":            4,
				"Degree":          "10° 00' - 13° 20' Sagittarius",
				"RulingPlanet":    "Ketu",
				"Characteristics": "Individuals born in this pada are introspective, wise, and have a strong sense of transformation.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Stable and Grounded", "Description": "Mool natives are known for their stability and grounding."},
			{"Characteristic": "Transformative and Resilient", "Description": "They are transformative, resilient, and possess a strong sense of foundation."},
			{"Characteristic": "Analytical and Investigative", "Description": "Mool natives are analytical, investigative, and have a love for grounding."},
			{"Characteristic": "Introspective and Wise", "Description": "They are introspective and wise, with a strong sense of transformation."},
		},
		"MaleCharacteristics":   "Men born under Mool Nakshatra are stable, grounded, and analytical. They are transformative and possess a strong sense of foundation.",
		"FemaleCharacteristics": "Women born under Mool Nakshatra are resilient, investigative, and stable. They are wise and possess a strong sense of transformation.",
		"Career": []map[string]string{
			{"Career": "Research and Analysis", "Description": "Mool natives have a strong sense of investigation and can excel in research and analysis."},
			{"Career": "Healthcare and Healing Professions", "Description": "Their transformative nature makes them suitable for careers in healthcare and healing professions."},
			{"Career": "Psychology and Counseling", "Description": "They are introspective and can succeed in psychology and counseling."},
			{"Career": "Spirituality and Mysticism", "Description": "Mool natives are wise and can pursue careers related to spirituality and mysticism."},
			{"Career": "Agriculture and Horticulture", "Description": "Their grounding nature makes them suitable for careers in agriculture and horticulture."},
		},
	},
	"PoorvaShada": {
		"Features": "Purva Ashadha Nakshatra represents invincibility, victory, and declaration. It is symbolized by a fan, indicating power and influence.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "13° 20' - 16° 40' Sagittarius",
				"RulingPlanet":    "Venus",
				"Characteristics": "Individuals born in this pada are powerful, influential, and possess a strong sense of victory.",
			},
			2: {
				"Pada":            2,
				"Degree":          "16° 40' - 20° 00' Sagittarius",
				"RulingPlanet":    "Venus",
				"Characteristics": "These individuals are invincible, determined, and have a strong connection to power.",
			},
			3: {
				"Pada":            3,
				"Degree":          "20° 00' - 23° 20' Sagittarius",
				"RulingPlanet":    "Venus",
				"Characteristics": "People in this pada are strategic, charismatic, and possess a love for influence.",
			},
			4: {
				"Pada":            4,
				"Degree":          "23° 20' - 26° 40' Sagittarius",
				"RulingPlanet":    "Venus",
				"Characteristics": "Individuals born in this pada are persuasive, ambitious, and have a strong sense of declaration.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Powerful and Influential", "Description": "Purva Ashadha natives are known for their power and influence."},
			{"Characteristic": "Invincible and Determined", "Description": "They are invincible, determined, and possess a strong sense of victory."},
			{"Characteristic": "Strategic and Charismatic", "Description": "Purva Ashadha natives are strategic, charismatic, and have a love for influence."},
			{"Characteristic": "Persuasive and Ambitious", "Description": "They are persuasive and ambitious, with a strong sense of declaration."},
		},
		"MaleCharacteristics":   "Men born under Purva Ashadha Nakshatra are powerful, influential, and strategic. They are invincible and possess a strong sense of victory.",
		"FemaleCharacteristics": "Women born under Purva Ashadha Nakshatra are determined, charismatic, and powerful. They are ambitious and possess a strong sense of influence.",
		"Career": []map[string]string{
			{"Career": "Leadership and Administration", "Description": "Purva Ashadha natives have a strong sense of power and can excel in leadership and administration."},
			{"Career": "Politics and Government", "Description": "Their influential nature makes them suitable for careers in politics and government."},
			{"Career": "Business and Entrepreneurship", "Description": "They are strategic and can succeed in business and entrepreneurship."},
			{"Career": "Law and Advocacy", "Description": "Purva Ashadha natives are persuasive and can pursue careers in law and advocacy."},
			{"Career": "Art and Performance", "Description": "Their charismatic nature makes them suitable for careers in art and performance."},
		},
	},
	"UttaraShada": {
		"Features": "Uttara Ashadha Nakshatra represents victory, leadership, and recognition. It is symbolized by an elephant tusk, indicating firmness and strength.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "26° 40' Sagittarius - 0° 00' Capricorn",
				"RulingPlanet":    "Sun",
				"Characteristics": "Individuals born in this pada are firm, strong, and possess a strong sense of leadership.",
			},
			2: {
				"Pada":            2,
				"Degree":          "0° 00' - 3° 20' Capricorn",
				"RulingPlanet":    "Sun",
				"Characteristics": "These individuals are determined, disciplined, and have a strong connection to victory.",
			},
			3: {
				"Pada":            3,
				"Degree":          "3° 20' - 6° 40' Capricorn",
				"RulingPlanet":    "Sun",
				"Characteristics": "People in this pada are ambitious, authoritative, and possess a love for recognition.",
			},
			4: {
				"Pada":            4,
				"Degree":          "6° 40' - 10° 00' Capricorn",
				"RulingPlanet":    "Sun",
				"Characteristics": "Individuals born in this pada are responsible, respected, and have a strong sense of firmness.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Firm and Strong", "Description": "Uttara Ashadha natives are known for their firmness and strength."},
			{"Characteristic": "Determined and Disciplined", "Description": "They are determined, disciplined, and possess a strong sense of leadership."},
			{"Characteristic": "Ambitious and Authoritative", "Description": "Uttara Ashadha natives are ambitious, authoritative, and have a love for recognition."},
			{"Characteristic": "Responsible and Respected", "Description": "They are responsible and respected, with a strong sense of firmness."},
		},
		"MaleCharacteristics":   "Men born under Uttara Ashadha Nakshatra are firm, strong, and ambitious. They are determined and possess a strong sense of leadership.",
		"FemaleCharacteristics": "Women born under Uttara Ashadha Nakshatra are disciplined, authoritative, and firm. They are respected and possess a strong sense of victory.",
		"Career": []map[string]string{
			{"Career": "Leadership and Administration", "Description": "Uttara Ashadha natives have a strong sense of firmness and can excel in leadership and administration."},
			{"Career": "Politics and Government", "Description": "Their determined nature makes them suitable for careers in politics and government."},
			{"Career": "Business and Entrepreneurship", "Description": "They are ambitious and can succeed in business and entrepreneurship."},
			{"Career": "Law and Judiciary", "Description": "Uttara Ashadha natives are authoritative and can pursue careers in law and judiciary."},
			{"Career": "Healthcare and Service Professions", "Description": "Their responsible nature makes them suitable for careers in healthcare and service professions."},
		},
	},
	"Shravana": {
		"Features": "Shravana Nakshatra represents learning, listening, and communication. It is symbolized by an ear, indicating wisdom and receptivity.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "10° 00' - 13° 20' Capricorn",
				"RulingPlanet":    "Moon",
				"Characteristics": "Individuals born in this pada are wise, receptive, and possess a strong sense of learning.",
			},
			2: {
				"Pada":            2,
				"Degree":          "13° 20' - 16° 40' Capricorn",
				"RulingPlanet":    "Moon",
				"Characteristics": "These individuals are communicative, intuitive, and have a strong connection to wisdom.",
			},
			3: {
				"Pada":            3,
				"Degree":          "16° 40' - 20° 00' Capricorn",
				"RulingPlanet":    "Moon",
				"Characteristics": "People in this pada are knowledgeable, articulate, and possess a love for communication.",
			},
			4: {
				"Pada":            4,
				"Degree":          "20° 00' - 23° 20' Capricorn",
				"RulingPlanet":    "Moon",
				"Characteristics": "Individuals born in this pada are perceptive, insightful, and have a strong sense of receptivity.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Wise and Receptive", "Description": "Shravana natives are known for their wisdom and receptivity."},
			{"Characteristic": "Communicative and Intuitive", "Description": "They are communicative, intuitive, and possess a strong sense of learning."},
			{"Characteristic": "Knowledgeable and Articulate", "Description": "Shravana natives are knowledgeable, articulate, and have a love for communication."},
			{"Characteristic": "Perceptive and Insightful", "Description": "They are perceptive and insightful, with a strong sense of receptivity."},
		},
		"MaleCharacteristics":   "Men born under Shravana Nakshatra are wise, receptive, and knowledgeable. They are communicative and possess a strong sense of learning.",
		"FemaleCharacteristics": "Women born under Shravana Nakshatra are intuitive, articulate, and wise. They are insightful and possess a strong sense of wisdom.",
		"Career": []map[string]string{
			{"Career": "Teaching", "Description": "Shravana natives are well-suited for careers in teaching due to their knowledge and communication skills."},
			{"Career": "Writing", "Description": "Their articulate nature makes them excellent writers."},
			{"Career": "Research", "Description": "Their intelligence makes them suitable for careers in research."},
			{"Career": "Administration", "Description": "Their discipline makes them suitable for administrative roles."},
		},
	},
	"Dhanishta": {
		"Features": "Dhanishta Nakshatra represents wealth, prosperity, and musical talent. It is symbolized by a drum, indicating rhythm and harmony.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "23° 20' - 26° 40' Capricorn",
				"RulingPlanet":    "Mars",
				"Characteristics": "Individuals born in this pada are ambitious, energetic, and possess leadership qualities.",
			},
			2: {
				"Pada":            2,
				"Degree":          "26° 40' - 30° 00' Capricorn",
				"RulingPlanet":    "Mars",
				"Characteristics": "These individuals are disciplined, determined, and have a strong sense of responsibility.",
			},
			3: {
				"Pada":            3,
				"Degree":          "0° 00' - 3° 20' Aquarius",
				"RulingPlanet":    "Mars",
				"Characteristics": "People in this pada are innovative, humanitarian, and have a unique approach to life.",
			},
			4: {
				"Pada":            4,
				"Degree":          "3° 20' - 6° 40' Aquarius",
				"RulingPlanet":    "Mars",
				"Characteristics": "Individuals born in this pada are progressive, intellectual, and possess a strong sense of community.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Ambitious and Energetic", "Description": "Dhanishta natives are known for their ambition and high energy levels."},
			{"Characteristic": "Disciplined and Determined", "Description": "They are disciplined, determined, and possess a strong sense of responsibility."},
			{"Characteristic": "Innovative and Humanitarian", "Description": "These individuals are innovative, humanitarian, and have a unique approach to life."},
			{"Characteristic": "Progressive and Intellectual", "Description": "They are progressive, intellectual, and possess a strong sense of community."},
		},
		"MaleCharacteristics":   "Men born under Dhanishta Nakshatra are ambitious, energetic, and possess leadership qualities. They are disciplined, determined, and have a strong sense of responsibility.",
		"FemaleCharacteristics": "Women born under Dhanishta Nakshatra are innovative, humanitarian, and have a unique approach to life. They are progressive, intellectual, and possess a strong sense of community.",
		"Career": []map[string]string{
			{"Career": "Music and Arts", "Description": "Dhanishta natives are well-suited for careers in music and the arts due to their rhythmic and harmonious nature."},
			{"Career": "Leadership Roles", "Description": "Their leadership qualities make them suitable for various leadership roles."},
			{"Career": "Social Work", "Description": "Their humanitarian nature makes them suitable for careers in social work."},
			{"Career": "Innovative Fields", "Description": "Their innovative approach makes them suitable for careers in technology and other innovative fields."},
		},
	},
	"Shatabhisha": {
		"Features": "Shatabhisha Nakshatra represents healing, secrets, and the unknown. It is symbolized by an empty circle, indicating mystery and introspection.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "6° 40' - 10° 00' Aquarius",
				"RulingPlanet":    "Rahu",
				"Characteristics": "Individuals born in this pada are introspective, analytical, and possess healing abilities.",
			},
			2: {
				"Pada":            2,
				"Degree":          "10° 00' - 13° 20' Aquarius",
				"RulingPlanet":    "Rahu",
				"Characteristics": "These individuals are secretive, intuitive, and have a deep understanding of the unknown.",
			},
			3: {
				"Pada":            3,
				"Degree":          "13° 20' - 16° 40' Aquarius",
				"RulingPlanet":    "Rahu",
				"Characteristics": "People in this pada are mysterious, analytical, and possess a strong sense of healing.",
			},
			4: {
				"Pada":            4,
				"Degree":          "16° 40' - 20° 00' Aquarius",
				"RulingPlanet":    "Rahu",
				"Characteristics": "Individuals born in this pada are introspective, intuitive, and have a deep understanding of mysteries.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Introspective and Analytical", "Description": "Shatabhisha natives are known for their introspection and analytical abilities."},
			{"Characteristic": "Secretive and Intuitive", "Description": "They are secretive, intuitive, and possess a deep understanding of the unknown."},
			{"Characteristic": "Mysterious and Healing", "Description": "These individuals are mysterious, analytical, and possess healing abilities."},
			{"Characteristic": "Introspective and Intuitive", "Description": "They are introspective, intuitive, and have a deep understanding of mysteries."},
		},
		"MaleCharacteristics":   "Men born under Shatabhisha Nakshatra are introspective, analytical, and possess healing abilities. They are secretive, intuitive, and have a deep understanding of the unknown.",
		"FemaleCharacteristics": "Women born under Shatabhisha Nakshatra are mysterious, analytical, and possess a strong sense of healing. They are introspective, intuitive, and have a deep understanding of mysteries.",
		"Career": []map[string]string{
			{"Career": "Healing Professions", "Description": "Shatabhisha natives are well-suited for careers in healing professions such as doctors, therapists, and healers."},
			{"Career": "Research and Analysis", "Description": "Their analytical abilities make them suitable for careers in research and analysis."},
			{"Career": "Secretive Roles", "Description": "Their secretive nature makes them suitable for careers in espionage, investigation, and other secretive roles."},
			{"Career": "Intuitive Fields", "Description": "Their intuitive nature makes them suitable for careers in fields that require intuition and understanding of the unknown."},
		},
	},
	"PurvaBhadrapada": {
		"Features": "Purva Bhadrapada Nakshatra represents transformation, spiritual awakening, and purification. It is symbolized by a two-faced man, indicating duality and spiritual growth.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "20° 00' - 23° 20' Aquarius",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "Individuals born in this pada are transformative, spiritually inclined, and possess dual characteristics.",
			},
			2: {
				"Pada":            2,
				"Degree":          "23° 20' - 26° 40' Aquarius",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "These individuals are spiritually awakened, intuitive, and have a strong sense of transformation.",
			},
			3: {
				"Pada":            3,
				"Degree":          "26° 40' - 30° 00' Aquarius",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "People in this pada are dual-natured, spiritually inclined, and possess transformative abilities.",
			},
			4: {
				"Pada":            4,
				"Degree":          "0° 00' - 3° 20' Pisces",
				"RulingPlanet":    "Jupiter",
				"Characteristics": "Individuals born in this pada are purifying, spiritually awakened, and possess dual characteristics.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Transformative and Spiritually Inclined", "Description": "Purva Bhadrapada natives are known for their transformative and spiritually inclined nature."},
			{"Characteristic": "Dual-Natured and Intuitive", "Description": "They are dual-natured, intuitive, and possess a strong sense of transformation."},
			{"Characteristic": "Spiritually Awakened and Purifying", "Description": "These individuals are spiritually awakened, intuitive, and possess purifying abilities."},
			{"Characteristic": "Dual Characteristics and Spiritual Growth", "Description": "They are dual-natured, spiritually inclined, and possess transformative abilities."},
		},
		"MaleCharacteristics":   "Men born under Purva Bhadrapada Nakshatra are transformative, spiritually inclined, and possess dual characteristics. They are spiritually awakened, intuitive, and have a strong sense of transformation.",
		"FemaleCharacteristics": "Women born under Purva Bhadrapada Nakshatra are dual-natured, spiritually inclined, and possess transformative abilities. They are spiritually awakened, intuitive, and possess purifying abilities.",
		"Career": []map[string]string{
			{"Career": "Spiritual and Religious Fields", "Description": "Purva Bhadrapada natives are well-suited for careers in spiritual and religious fields."},
			{"Career": "Transformative Roles", "Description": "Their transformative abilities make them suitable for careers in psychology, therapy, and other transformative roles."},
			{"Career": "Intuitive Professions", "Description": "Their intuitive nature makes them suitable for careers in fields that require intuition and understanding of spiritual growth."},
			{"Career": "Purifying Roles", "Description": "Their purifying nature makes them suitable for careers in health, wellness, and purification roles."},
		},
	},
	"UttaraBhadrapada": {
		"Features": "Uttara Bhadrapada Nakshatra represents stability, depth, and wisdom. It is symbolized by a snake in water, indicating depth and stability.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "3° 20' - 6° 40' Pisces",
				"RulingPlanet":    "Saturn",
				"Characteristics": "Individuals born in this pada are stable, wise, and possess deep understanding.",
			},
			2: {
				"Pada":            2,
				"Degree":          "6° 40' - 10° 00' Pisces",
				"RulingPlanet":    "Saturn",
				"Characteristics": "These individuals are deep, insightful, and have a strong sense of stability.",
			},
			3: {
				"Pada":            3,
				"Degree":          "10° 00' - 13° 20' Pisces",
				"RulingPlanet":    "Saturn",
				"Characteristics": "People in this pada are wise, stable, and possess a deep understanding of life.",
			},
			4: {
				"Pada":            4,
				"Degree":          "13° 20' - 16° 40' Pisces",
				"RulingPlanet":    "Saturn",
				"Characteristics": "Individuals born in this pada are insightful, wise, and have a strong sense of stability.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Stable and Wise", "Description": "Uttara Bhadrapada natives are known for their stability and wisdom."},
			{"Characteristic": "Deep and Insightful", "Description": "They are deep, insightful, and possess a strong sense of stability."},
			{"Characteristic": "Wise and Stable", "Description": "These individuals are wise, stable, and possess a deep understanding of life."},
			{"Characteristic": "Insightful and Wise", "Description": "They are insightful, wise, and have a strong sense of stability."},
		},
		"MaleCharacteristics":   "Men born under Uttara Bhadrapada Nakshatra are stable, wise, and possess deep understanding. They are deep, insightful, and have a strong sense of stability.",
		"FemaleCharacteristics": "Women born under Uttara Bhadrapada Nakshatra are wise, stable, and possess a deep understanding of life. They are insightful, wise, and have a strong sense of stability.",
		"Career": []map[string]string{
			{"Career": "Teaching and Wisdom Professions", "Description": "Uttara Bhadrapada natives are well-suited for careers in teaching and wisdom professions."},
			{"Career": "Insightful Roles", "Description": "Their deep understanding makes them suitable for careers in psychology, counseling, and other insightful roles."},
			{"Career": "Stable Professions", "Description": "Their stability makes them suitable for careers in management, administration, and other stable professions."},
			{"Career": "Wisdom Fields", "Description": "Their wisdom makes them suitable for careers in spiritual and wisdom-related fields."},
		},
	},
	"Revati": {
		"Features": "Revati Nakshatra represents prosperity, nourishment, and travel. It is symbolized by a fish, indicating movement and abundance.",
		"Pada": map[int]map[string]interface{}{
			1: {
				"Pada":            1,
				"Degree":          "16° 40' - 20° 00' Pisces",
				"RulingPlanet":    "Mercury",
				"Characteristics": "Individuals born in this pada are prosperous, nurturing, and possess a sense of movement.",
			},
			2: {
				"Pada":            2,
				"Degree":          "20° 00' - 23° 20' Pisces",
				"RulingPlanet":    "Mercury",
				"Characteristics": "These individuals are abundant, nurturing, and have a strong sense of prosperity.",
			},
			3: {
				"Pada":            3,
				"Degree":          "23° 20' - 26° 40' Pisces",
				"RulingPlanet":    "Mercury",
				"Characteristics": "People in this pada are nurturing, prosperous, and possess a sense of movement.",
			},
			4: {
				"Pada":            4,
				"Degree":          "0° 00' - 3° 20' Aries",
				"RulingPlanet":    "Mercury",
				"Characteristics": "Individuals born in this pada are prosperous, nurturing, and possess a sense of movement.",
			},
		},
		"General Characteristics": []map[string]string{
			{"Characteristic": "Prosperous and Nurturing", "Description": "Revati natives are known for their prosperity and nurturing nature."},
			{"Characteristic": "Abundant and Nurturing", "Description": "They are abundant, nurturing, and possess a strong sense of prosperity."},
			{"Characteristic": "Nurturing and Prosperous", "Description": "These individuals are nurturing, prosperous, and possess a sense of movement."},
			{"Characteristic": "Prosperous and Nurturing", "Description": "They are prosperous, nurturing, and possess a sense of movement."},
		},
		"MaleCharacteristics":   "Men born under Revati Nakshatra are prosperous, nurturing, and possess a sense of movement. They are abundant, nurturing, and have a strong sense of prosperity.",
		"FemaleCharacteristics": "Women born under Revati Nakshatra are empathetic, artistic, courageous, spiritually inclined, and dedicated to their family and responsibilities.",
		"Career": []map[string]string{
			{"Career": "Nourishing Professions", "Description": "Revati natives are well-suited for careers in nourishing professions such as chefs, dietitians, and caregivers."},
			{"Career": "Prosperous Fields", "Description": "Their prosperity makes them suitable for careers in finance, business, and other prosperous fields."},
			{"Career": "Travel and Movement", "Description": "Their sense of movement makes them suitable for careers in travel, logistics, and other fields requiring movement."},
			{"Career": "Nurturing Roles", "Description": "Their nurturing nature makes them suitable for careers in healthcare, education, and other nurturing roles."},
		},
	},
}
